# Generated by Django 4.0 on 2021-12-29 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_name', models.CharField(max_length=200)),
                ('stud_email', models.EmailField(max_length=254)),
                ('stud_contact', models.CharField(max_length=12)),
                ('stud_course', models.CharField(max_length=200)),
                ('stud_stud_id', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
