# Generated by Django 4.0.2 on 2022-04-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_role',
            new_name='stud_course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stud_salary',
            new_name='stud_stud_id',
        ),
    ]
