# Generated by Django 4.0.2 on 2022-04-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_stud_role_student_stud_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_contact',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_course',
            field=models.CharField(max_length=200, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_stud_id',
            field=models.IntegerField(verbose_name='Student ID'),
        ),
    ]
